openapi: 3.0.3
info:
  title: TestnetAPI
  description: |-
  version: 0.1.0
servers:
  - url: /api/v1
paths:
  /register:
    post:
      description: Register new user into database
      tags:
        - Authorization
      security: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: "awesomecat@meow.com"
                password:
                  type: string
      responses:
        '200':
          description: gets jwt token
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: 'abcs#smnds232m###21mn'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /login:
    post:
      description: Signin in
      tags:
        - Authorization
      security: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: "awesomecat@meow.com"
                password:
                  type: string
      responses:
        '200':
          description: gets jwt token
          content:
            application/json:
              schema:
                properties:
                  access_token:
                    type: string
                    example: 'abcs#smnds232m###21mn'
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
            type: string
    StatusOk:
      type: object
      properties:
        status:
          type: string
          example: 'OK'


security:
  - bearerAuth: []